BOX1: 
  IP: '10.8.0.11'
  OFFSET: '0'
  KRANID: '07k'
  
BOX2: 
  IP: '10.8.0.21'
  OFFSET: '0'
  KRANID: '07g'

BOX3: 
  IP: '10.8.0.31'
  OFFSET: '0'
  KRANID: '08k'

BOX5: 
  IP: '10.8.0.51'
  OFFSET: '0'
  KRANID: '08g'

BOX4: 
  IP: '10.8.0.41'
  OFFSET: '0'
  KRANID: '09k'

BOX6: 
  IP: '10.8.0.61'
  OFFSET: '0'
  KRANID: 'bas'
