BOX1: 
  IP: '10.8.0.11'
  OFFSET: '6'
  KRANID: '25k'
  
BOX2: 
  IP: '10.8.0.21'
  OFFSET: '6'
  KRANID: '25g'

BOX3: 
  IP: '10.8.0.31'
  OFFSET: '6'
  KRANID: '26k'

BOX5: 
  IP: '10.8.0.51'
  OFFSET: '6'
  KRANID: '26g'

BOX4: 
  IP: '10.8.0.41'
  OFFSET: '6'
  KRANID: '09k'

BOX6: 
  IP: '10.8.0.61'
  OFFSET: '0'
  KRANID: 'bas'
